const liturgyTOC = {
    antifon1: 'Первый антифон',
    antifon2: 'Второй антифон',
    antifon3: 'Третий антифон',
    malyVhod: 'Малый вход',
    trisvatoe: 'Трисвятая песнь',
    apostol: 'Чтение Апостола',
    gospel: 'Чтение Евангелия',
    sugubaja: 'Сугубая ектения',
    oglashaemie: 'Отпуст оглашаемых',
    vernie: 'Литургия верных',
    vhod: 'Вход',
    prinoshenie: 'Молитва приношения',
    tselovanie: 'Целование мира',
    simvol: 'Символ веры',
    anafora: 'Анафора',
    prefacio: 'Вводная часть',
    anamnesis: 'Воспоминание',
    epiclisis: 'Призывание',
    hodataistvo: 'Ходатайство',
    ourfather: 'Молитва перед причащением',
    glavopriklon: 'Главопреклонная',
    prichashenie: 'Святое причащение',
    otpust: 'Отпуст',
};
export default liturgyTOC;
