export const GET_DAY = 'GET_DAY',
    GET_DAY_SUCCESS = 'GET_DAY_SUCCESS',
    GET_DAY_ERROR = 'GET_DAY_ERROR',
    GET_READING = 'GET_DAY',
    GET_READING_SUCCESS = 'GET_READING_SUCCESS',
    GET_READING_ERROR = 'GET_READING_ERROR';
